### PR TITLE
Merge pull request #1 from skirb1/master

### PR DESCRIPTION
**Pull request by DTeamCMSC**
-redo

### CODE REVIEW

**Comment by DTeamCMSC** [comment]
I noticed in your header you had studentmenu.php?
what did you want to with that and also my phone is as dead as my soul
right now(tons of work to do)

On Thu, Apr 30, 2015 at 4:08 PM, Sarah Kirby notifications@github.com
wrote:

> Merged #1 https://github.com/skirb1/Project2-Student/pull/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skirb1/Project2-Student/pull/1#event-294456537.

## 

Thanks!,
Damola Adediran

**Comment by skirb1** [comment]
Oh I don't think we need it anymore. Lol I'm about to head to the library to work on this, if you wanna join you're welcome to!

**Comment by DTeamCMSC** [comment]
I am currently off campus sadly :\ I will be back tomorrow morning so if
you get any time, we can work on it in the library.

On Thu, Apr 30, 2015 at 6:24 PM, Sarah Kirby notifications@github.com
wrote:

> Oh I don't think we need it anymore. Lol I'm about to head to the library
> to work on this, if you wanna join you're welcome to!
> 
> Sent from my iPhone
> 
> > On Apr 30, 2015, at 5:39 PM, Damola Adediran notifications@github.com
> > wrote:
> > 
> > I noticed in your header you had studentmenu.php?
> > what did you want to with that and also my phone is as dead as my soul
> > right now(tons of work to do)
> > 
> > On Thu, Apr 30, 2015 at 4:08 PM, Sarah Kirby notifications@github.com
> > wrote:
> > 
> > > Merged #1 https://github.com/skirb1/Project2-Student/pull/1.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/skirb1/Project2-Student/pull/1#event-294456537.
> > 
> > ## 
> > 
> > Thanks!,
> > Damola Adediran
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skirb1/Project2-Student/pull/1#issuecomment-97989073.

## 

Thanks!,
Damola Adediran

**Comment by skirb1** [comment]
Ok ill try be in the library tomorrow morning. Most of the advisor stuff is
implemented now, it doesn't update groups yet when the advisor signs up for
a group time, and we still need another page for setting the number of
students in a group. But if you meet with an advisor tomorrow show them
what we have to get feedback.

I have a few questions for an advisor too, are you meeting with them in the
morning? I can email you the questions or meet you in the library tomorrow.
Lmk.

On Thu, Apr 30, 2015 at 8:02 PM, Damola Adediran notifications@github.com
wrote:

> I am currently off campus sadly :\ I will be back tomorrow morning so if
> you get any time, we can work on it in the library.
> 
> On Thu, Apr 30, 2015 at 6:24 PM, Sarah Kirby notifications@github.com
> wrote:
> 
> > Oh I don't think we need it anymore. Lol I'm about to head to the library
> > to work on this, if you wanna join you're welcome to!
> > 
> > Sent from my iPhone
> > 
> > > On Apr 30, 2015, at 5:39 PM, Damola Adediran <notifications@github.com
> > 
> > wrote:
> > 
> > > I noticed in your header you had studentmenu.php?
> > > what did you want to with that and also my phone is as dead as my soul
> > > right now(tons of work to do)
> > > 
> > > On Thu, Apr 30, 2015 at 4:08 PM, Sarah Kirby <notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > Merged #1 https://github.com/skirb1/Project2-Student/pull/1.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/skirb1/Project2-Student/pull/1#event-294456537.
> > > 
> > > ## 
> > > 
> > > Thanks!,
> > > Damola Adediran
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/skirb1/Project2-Student/pull/1#issuecomment-97989073
> > .
> 
> ## 
> 
> Thanks!,
> Damola Adediran
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skirb1/Project2-Student/pull/1#issuecomment-98005042.

## 

Sarah Kirby
Computer Science '17
University of Maryland Baltimore County
skirb1@umbc.edu
(240) 498-6572

**Comment by DTeamCMSC** [comment]
I had to rescheduele the appointment since I slept through it sadly

On Thu, Apr 30, 2015 at 10:25 PM, Sarah Kirby notifications@github.com
wrote:

> Ok ill try be in the library tomorrow morning. Most of the advisor stuff is
> implemented now, it doesn't update groups yet when the advisor signs up for
> a group time, and we still need another page for setting the number of
> students in a group. But if you meet with an advisor tomorrow show them
> what we have to get feedback.
> 
> I have a few questions for an advisor too, are you meeting with them in the
> morning? I can email you the questions or meet you in the library tomorrow.
> Lmk.
> 
> On Thu, Apr 30, 2015 at 8:02 PM, Damola Adediran <notifications@github.com
> 
> > wrote:
> > 
> > I am currently off campus sadly :\ I will be back tomorrow morning so if
> > you get any time, we can work on it in the library.
> > 
> > On Thu, Apr 30, 2015 at 6:24 PM, Sarah Kirby notifications@github.com
> > wrote:
> > 
> > > Oh I don't think we need it anymore. Lol I'm about to head to the
> > > library
> > > to work on this, if you wanna join you're welcome to!
> > > 
> > > Sent from my iPhone
> > > 
> > > > On Apr 30, 2015, at 5:39 PM, Damola Adediran <
> > > > notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > I noticed in your header you had studentmenu.php?
> > > > what did you want to with that and also my phone is as dead as my
> > > > soul
> > > > right now(tons of work to do)
> > > > 
> > > > On Thu, Apr 30, 2015 at 4:08 PM, Sarah Kirby <
> > > > notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > Merged #1 https://github.com/skirb1/Project2-Student/pull/1.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/skirb1/Project2-Student/pull/1#event-294456537
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Thanks!,
> > > > Damola Adediran
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/skirb1/Project2-Student/pull/1#issuecomment-97989073
> > > .
> > 
> > ## 
> > 
> > Thanks!,
> > Damola Adediran
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/skirb1/Project2-Student/pull/1#issuecomment-98005042
> > .
> 
> ## 
> 
> Sarah Kirby
> Computer Science '17
> University of Maryland Baltimore County
> skirb1@umbc.edu
> (240) 498-6572
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/skirb1/Project2-Student/pull/1#issuecomment-98028311.

## 

Thanks!,
Damola Adediran

**Comment by DTeamCMSC** [comment]
http://www.humanmetrics.com/cgi-win/jtypes2.asp

type test hype!

On Fri, May 1, 2015 at 7:34 PM, Damola Adediran dadedir1@umbc.edu wrote:

> I had to rescheduele the appointment since I slept through it sadly
> 
> On Thu, Apr 30, 2015 at 10:25 PM, Sarah Kirby notifications@github.com
> wrote:
> 
> > Ok ill try be in the library tomorrow morning. Most of the advisor stuff
> > is
> > implemented now, it doesn't update groups yet when the advisor signs up
> > for
> > a group time, and we still need another page for setting the number of
> > students in a group. But if you meet with an advisor tomorrow show them
> > what we have to get feedback.
> > 
> > I have a few questions for an advisor too, are you meeting with them in
> > the
> > morning? I can email you the questions or meet you in the library
> > tomorrow.
> > Lmk.
> > 
> > On Thu, Apr 30, 2015 at 8:02 PM, Damola Adediran <
> > notifications@github.com>
> > wrote:
> > 
> > > I am currently off campus sadly :\ I will be back tomorrow morning so if
> > > you get any time, we can work on it in the library.
> > > 
> > > On Thu, Apr 30, 2015 at 6:24 PM, Sarah Kirby notifications@github.com
> > > wrote:
> > > 
> > > > Oh I don't think we need it anymore. Lol I'm about to head to the
> > > > library
> > > > to work on this, if you wanna join you're welcome to!
> > > > 
> > > > Sent from my iPhone
> > > > 
> > > > > On Apr 30, 2015, at 5:39 PM, Damola Adediran <
> > > > > notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > I noticed in your header you had studentmenu.php?
> > > > > what did you want to with that and also my phone is as dead as my
> > > > > soul
> > > > > right now(tons of work to do)
> > > > > 
> > > > > On Thu, Apr 30, 2015 at 4:08 PM, Sarah Kirby <
> > > > > notifications@github.com
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > Merged #1 https://github.com/skirb1/Project2-Student/pull/1.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > > > https://github.com/skirb1/Project2-Student/pull/1#event-294456537>.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Thanks!,
> > > > > Damola Adediran
> > > > > —
> > > > > Reply to this email directly or view it on GitHub.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/skirb1/Project2-Student/pull/1#issuecomment-97989073
> > > > .
> > > 
> > > ## 
> > > 
> > > Thanks!,
> > > Damola Adediran
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/skirb1/Project2-Student/pull/1#issuecomment-98005042>.
> > 
> > ## 
> > 
> > Sarah Kirby
> > Computer Science '17
> > University of Maryland Baltimore County
> > skirb1@umbc.edu
> > (240) 498-6572
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/skirb1/Project2-Student/pull/1#issuecomment-98028311
> > .
> 
> ## 
> 
> Thanks!,
> Damola Adediran

## 

Thanks!,
Damola Adediran

**Pull request merged**
